### ISSUE TITLE
Focusing-outlet scrolls to top when child route's model is refreshed

### ISSUE THREAD

**Issue by steveszc** [ember-a11y/ember-a11y#60] opened 2017-12-20 23:24 UTC
When a focusing-outlet's child route's model is refreshed, the browser scroll position jumps to the top of the page. This is not expected and seems wrong. This does not occur when using a normal outlet. I have created a minimal reproduction repo (link below).

### Reproduction
1. Clone and run this ember app: https://github.com/steveszc/ember-a11y-scroll-reproduction
2. Follow instructions provided by the app
(issue is reproducible in Firefox and Chrome)

### Actual
When a focusing-outlet's child route's model is refreshed, the browser scroll position jumps to the top of the page.

### Expected
When the child model is refreshed, browser scroll position should not be changed. 
(this is the default behavior of a normal outlet)

**Comment by Robdel12** [comment] 2017-12-21 04:03
This one is tricky. _Technically_ calling `refresh()` on the route is a route transition. When `.refresh()` is called it [technically is a pivot route](https://github.com/ember-a11y/ember-a11y/blob/master/addon/mixins/focusing.js#L85).

I agree that this is undesirable behavior. Thank you for the awesome replication repo!!

**Comment by nathanhammond** [comment] 2018-09-17 17:58
This is expected behavior, but it should be tunable. The reason this is happening is because it is setting focus to the pivot route, which is correct since that's a "new" transition.

Setting of focus scrolls the element into view.

The fix here is to provide an integration into `ember-router-scroll` that provides better defaults for scroll behavior.

That makes this and #53 approximately duplicates.

**Comment by nathanhammond** [comment] 2018-12-10 23:53
This issue is resolved by #71.

As a consequence, *all* refresh transitions should now maintain the same position as before; no scroll position changes occur as a consequence of setting focus.

**Closed by nathanhammond** 2018-12-10 23:53 UTC
Labels: Bug
