### ISSUE TITLE
ScrollTo behavior in focussing-outlet breaks ember-router-scroll

### ISSUE THREAD

**Issue by eshtadc** [ember-a11y/ember-a11y#53] opened 2017-08-09 14:49 UTC
The focussing-outlet implements functionality that is intended to prevent scrolling when the focus is set programmatically. There are cases when this is not the desired behavior. For example, when using ember-router-scroll, the application should respect ember-router-scroll's scroll positions rather than overriding on the scroll event. Given that this functionality is purely for users who are not visually impaired it seems that it should be overridable.

This is somewhat related to https://github.com/ember-a11y/ember-a11y/issues/9 in that similar issues are being discussed there.

### Reproduction
On an application with both ember-router-scroll and ember-a11y focusing-outlet, click a link-to that is positioned down the page (such that scrolling is required).

### Actual
Changing routes leaves the user at the scroll position that they left on the previous route.

### Expected
Page is automatically scrolled back to (0,0) per ember-router-scroll.

**Comment by eshtadc** [comment] 2017-08-09 14:51
I'd like to work on a PR that would address this. Seems like the best approach would be to make it configurable whether ember-a11y should preserve the scroll position when changing routes.

**Comment by BrennanRoberts** [comment] 2018-01-27 21:23
Does anyone have a technique for resetting scroll position after each page transition in a way that doesn't cause [this line](https://github.com/ember-a11y/ember-a11y/blob/abbc629a6730d4bb31bb4b3568ed985e668dfd8a/addon/mixins/focusing.js#L50) to cancel their scroll attempt (and then fail to catch the scroll caused by ember-a11y's `focus()`)?

**Comment by nathanhammond** [comment] 2018-12-10 23:51
Addressed by #71.

**Closed by nathanhammond** 2018-12-10 23:51 UTC
