### ISSUE TITLE
Crashes with Ember 3.10

### ISSUE THREAD

**Issue by dustinsoftware** [ember-a11y/ember-a11y#76] opened 2019-05-21 14:00 UTC
The shape of the arguments passed to `willTransition` appears to have changed in the Ember 3.10 release, which breaks this addon.

![image](https://user-images.githubusercontent.com/942358/58101791-3974e980-7bae-11e9-99e6-5b3f8c4ea053.png)

![image](https://user-images.githubusercontent.com/942358/58102099-c28c2080-7bae-11e9-8357-3176fd6ae166.png)

### Reproduction
1. Trigger a route transition on an Ember 3.10 app
2. Observe crash

Happy to PR a fix if you have time to review it.

**Comment by nathanhammond** [comment] 2019-05-21 20:10
This and #75 are duplicates. Arguably this is an upstream issue as the existing `handlerInfo` world was intended to continue working until 4.0.

/cc @rwjblue @chadhietala

**Comment by nathanhammond** [comment] 2019-05-21 20:16
If you can get a PR up I can certainly review and release in a timely manner. The main thing is that the handlers need to have an identity comparison that isn’t bound to object identity.

I’m not going to have time to dive in myself until May 27 if I’m the one that needs to get a fix in place but will commit to reviewing a PR for this within 24 hours as long as you ping me on Discord.

**Comment by dustinsoftware** [comment] 2019-05-30 13:30
Sorry for ghosting on this issue. I'm not going to have time after all to work on a fix...

**Comment by mehulkar** [comment] 2019-06-04 17:20
@dustinsoftware can we close this in favor of #75 since it's older?

**Comment by MelSumner** [comment] 2019-06-04 18:35
Duplicate of #75 - closing this issue as a result.

**Closed by MelSumner** 2019-06-04 18:35 UTC
